### ISSUE TITLE
[PE-D][Tester D] Events from the past can be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F09-1/tp#218]
![Screenshot 2024-11-08 at 5.17.41 PM.png](https://raw.githubusercontent.com/oolongwater/ped/main/files/93af8911-6b42-41c4-b3da-c470ea6f37c8.png)

Events from the past can be added, perhaps current date checks can be added if this is considered unwanted.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: oolongwater/ped#13

**Comment by limyixiang** [comment]
I don't think this is a bug... I don't see an issue with allowing events from the past to be added into ClubConnect.
Let's picture a scenario:
1. The Computing Club's President has just decided to start using ClubConnect.
2. He wants to migrate the data from his previous event list, e.g. Excel sheet, into ClubConnect for easier reference, so that all his events are in one place.
3. He would need to be able to add past events into ClubConnect.
